package repositories;

import entities.Entity;
import repositories.interfaces.Repository;

public abstract class BaseRepository<T extends Entity> implements Repository<T> {
    protected final T[] data;
    private long autogeneratedId;

    protected BaseRepository(T[] data) {
        this.data = data;
        this.autogeneratedId = data.length;
    }

    public T getById(long id) {
        for (T t : data) {
            if (t.getId() == id) {
                return t;
            }
        }
        return null;
    }

    public T add(T t) {
        for (int i = 0; i < data.length; i++) {
            if (data[i] == null) {
                t.setId(autogeneratedId);
                data[i] = t;
                autogeneratedId++;
                return t;
            }
        }
        return null;
    }

    public boolean delete(long id) {
        for (int i = 0; i < data.length; i++) {
            if (data[i].getId() == id) {
                data[i] = null;
                return true;
            }
        }
        return false;
    }

}
